# Generated by Django 4.2.4 on 2024-05-20 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('tree_name', models.TextField(max_length=100)),
                ('tree_scientific_name', models.TextField(max_length=200)),
                ('tree_description', models.TextField(max_length=10000)),
                ('search_link_key', models.TextField(max_length=200)),
                ('author_name', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
