# Generated by Django 4.2.4 on 2024-05-20 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_rename_author_name_tree_author_name_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tree',
            old_name='author_name_id',
            new_name='author_name',
        ),
    ]
