# Generated by Django 4.2.4 on 2024-05-20 06:34

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('details', '0004_rename_author_name_id_tree_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='author_name',
            field=models.ForeignKey(default=django.contrib.auth.models.AbstractUser.get_full_name, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
