# Generated by Django 4.2.4 on 2024-05-20 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0009_alter_tree_author_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tree',
            old_name='author_name',
            new_name='created_by',
        ),
    ]
